# Generated by Django 5.2.8 on 2026-04-05 15:10

import django.db.models.deletion
from django.db import migrations, models


def seed_mt_retailer(apps, schema_editor):
    Retailer = apps.get_model('tenants', 'Retailer')
    Retailer.objects.get_or_create(
        code='MT',
        defaults={'name': 'Manish Traders', 'is_active': True},
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0003_alter_store_shop_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Retailer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "primary_store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="locations.store",
                    ),
                ),
            ],
            options={
                "db_table": "retailers",
                "ordering": ["code"],
            },
        ),
        migrations.RunPython(seed_mt_retailer, migrations.RunPython.noop),
    ]
