# Generated by Django 5.2.8 on 2025-11-27 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_make_sku_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_image', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label', to='catalog.barcode')),
            ],
            options={
                'db_table': 'barcode_labels',
            },
        ),
    ]
