# Generated by Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_barcode_tag'),
    ]

    operations = [
        # Remove selling_price fields
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='selling_price',
        ),
        # Rename cost_price to purchase_price
        migrations.RenameField(
            model_name='product',
            old_name='cost_price',
            new_name='purchase_price',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='cost_price',
            new_name='purchase_price',
        ),
        # Add can_go_below_purchase_price field
        migrations.AddField(
            model_name='product',
            name='can_go_below_purchase_price',
            field=models.BooleanField(default=False),
        ),
    ]
