# Generated by Django 5.2.8 on 2025-12-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_selling_price_rename_cost_to_purchase_add_can_go_below'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='tag',
            field=models.CharField(choices=[('new', 'NEW (Fresh)'), ('sold', 'Sold'), ('returned', 'Returned'), ('defective', 'Defective'), ('unknown', 'Unknown')], default='new', max_length=20),
        ),
    ]
