# Generated by Django 5.2.8 on 2025-12-11 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_barcode_tag"),
        ("purchasing", "0002_remove_directpurchaseline_purchase_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="purchase_price",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="purchase_price",
        ),
        migrations.AddField(
            model_name="barcode",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="barcodes",
                to="purchasing.purchase",
            ),
        ),
        migrations.AddField(
            model_name="barcode",
            name="purchase_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="barcodes",
                to="purchasing.purchaseitem",
            ),
        ),
    ]
