# Generated by Django 5.2.8 on 2025-12-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_remove_product_purchase_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barcode",
            name="tag",
            field=models.CharField(
                choices=[
                    ("new", "NEW (Fresh)"),
                    ("sold", "Sold"),
                    ("returned", "Returned"),
                    ("defective", "Defective"),
                    ("unknown", "Unknown"),
                    ("in-cart", "In Cart"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
