# Generated by Django 5.2.8 on 2025-12-26 06:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_defective_product_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="defectiveproductmoveout",
            name="total_adjustment",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
