# Generated by Django 5.2.8 on 2026-01-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_defectiveproductmoveout_total_adjustment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barcode",
            name="tag",
            field=models.CharField(
                choices=[
                    ("new", "NEW (Fresh)"),
                    ("sold", "Sold"),
                    ("returned", "Returned"),
                    ("defective", "Defective"),
                    ("unknown", "Unknown"),
                    ("in-cart", "In Cart"),
                ],
                db_index=True,
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
