# Generated by Django 5.2.8 on 2026-01-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_add_short_code_to_barcode"),
        ("purchasing", "0005_add_selling_price_to_purchase_item"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="barcode",
            index=models.Index(
                fields=["product", "tag"], name="idx_barcode_product_tag"
            ),
        ),
        migrations.AddIndex(
            model_name="barcode",
            index=models.Index(
                fields=["tag", "product"], name="idx_barcode_tag_product"
            ),
        ),
        migrations.AddIndex(
            model_name="barcode",
            index=models.Index(
                fields=["purchase", "tag"], name="idx_barcode_purchase_tag"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-updated_at", "-created_at"], name="idx_product_updated"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="idx_product_category_active"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["brand", "is_active"], name="idx_product_brand_active"
            ),
        ),
    ]
