# Generated by Django 5.2.8 on 2026-04-04 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_soft_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barcode",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="barcodes",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="barcode",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="barcodes",
                to="catalog.productvariant",
            ),
        ),
    ]
