# Generated by Django 5.2.8 on 2026-04-04 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_barcode_product_set_null_on_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defectiveproductitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="defective_move_out_items",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="productcomponent",
            name="component_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_in_bundles",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="productcomponent",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="components",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="variants",
                to="catalog.product",
            ),
        ),
    ]
