# Generated by Django 5.2.8 on 2026-04-05 15:10

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


def backfill_catalog_retailer(apps, schema_editor):
    Retailer = apps.get_model('tenants', 'Retailer')
    r = Retailer.objects.filter(code='MT').first()
    if not r:
        r = Retailer.objects.create(code='MT', name='Manish Traders', is_active=True)
    Category = apps.get_model('catalog', 'Category')
    Brand = apps.get_model('catalog', 'Brand')
    TaxRate = apps.get_model('catalog', 'TaxRate')
    Product = apps.get_model('catalog', 'Product')
    ProductVariant = apps.get_model('catalog', 'ProductVariant')
    Barcode = apps.get_model('catalog', 'Barcode')
    DefectiveProductMoveOut = apps.get_model('catalog', 'DefectiveProductMoveOut')

    Category.objects.filter(retailer_id__isnull=True).update(retailer_id=r.id)
    Brand.objects.filter(retailer_id__isnull=True).update(retailer_id=r.id)
    TaxRate.objects.filter(retailer_id__isnull=True).update(retailer_id=r.id)
    Product.objects.filter(retailer_id__isnull=True).update(retailer_id=r.id)
    for pv in ProductVariant.objects.filter(retailer_id__isnull=True).select_related('product'):
        if pv.product_id and pv.product.retailer_id:
            ProductVariant.objects.filter(pk=pv.pk).update(retailer_id=pv.product.retailer_id)
    for b in Barcode.objects.filter(retailer_id__isnull=True).select_related('product', 'variant'):
        rid = None
        if b.product_id and b.product.retailer_id:
            rid = b.product.retailer_id
        elif b.variant_id and b.variant.product_id:
            p = Product.objects.filter(pk=b.variant.product_id).first()
            if p and p.retailer_id:
                rid = p.retailer_id
        if rid:
            Barcode.objects.filter(pk=b.pk).update(retailer_id=rid)
    Barcode.objects.filter(retailer_id__isnull=True).update(retailer_id=r.id)
    for mo in DefectiveProductMoveOut.objects.filter(retailer_id__isnull=True).select_related('store'):
        if mo.store_id and mo.store.retailer_id:
            DefectiveProductMoveOut.objects.filter(pk=mo.pk).update(retailer_id=mo.store.retailer_id)
    DefectiveProductMoveOut.objects.filter(retailer_id__isnull=True).update(retailer_id=r.id)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_safer_fk_on_delete"),
        ("locations", "0004_multitenant_phase1"),
        ("tenants", "0001_multitenant_phase1"),
    ]

    operations = [
        migrations.AddField(
            model_name="barcode",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="barcodes",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brands",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="defectiveproductmoveout",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="defective_move_outs",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_rates",
                to="tenants.retailer",
            ),
        ),
        migrations.AlterField(
            model_name="barcode",
            name="barcode",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="barcode",
            name="short_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Short barcode identifier without date (e.g., FRAM-0001)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="defectiveproductmoveout",
            name="move_out_number",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.RunPython(backfill_catalog_retailer, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="barcode",
            constraint=models.UniqueConstraint(
                fields=("retailer", "barcode"), name="uniq_barcode_retailer_barcode"
            ),
        ),
        migrations.AddConstraint(
            model_name="barcode",
            constraint=models.UniqueConstraint(
                condition=Q(short_code__isnull=False) & ~Q(short_code=''),
                fields=("retailer", "short_code"),
                name="uniq_barcode_retailer_short_code_nonnull",
            ),
        ),
        migrations.AddConstraint(
            model_name="brand",
            constraint=models.UniqueConstraint(
                fields=("retailer", "name"), name="uniq_brand_retailer_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="defectiveproductmoveout",
            constraint=models.UniqueConstraint(
                fields=("retailer", "move_out_number"),
                name="uniq_defective_moveout_retailer_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=Q(sku__isnull=False) & ~Q(sku=''),
                fields=("retailer", "sku"),
                name="uniq_product_retailer_sku_nonnull",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                fields=("retailer", "sku"), name="uniq_variant_retailer_sku"
            ),
        ),
    ]
