# Generated by Django 5.2.8 on 2026-05-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_safer_fk_on_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.TextField(blank=True, default=""),
        ),
    ]
