# Generated by Django 5.2.8 on 2026-05-05 07:35

import backend.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_product_image_textfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=backend.core.storage.ProductImageStorage(),
                upload_to="mt-images/",
            ),
        ),
    ]
