# Generated by Django 5.2.8 on 2026-04-20 13:34

from django.db import migrations, models
import django.db.models.deletion


def backfill_barcode_location_from_purchase(apps, schema_editor):
    Barcode = apps.get_model('catalog', 'Barcode')
    for bc in Barcode.objects.select_related('purchase').all():
        purchase = getattr(bc, 'purchase', None)
        if not purchase:
            continue
        update = {}
        if getattr(purchase, 'store_id', None):
            update['current_store_id'] = purchase.store_id
            update['current_warehouse_id'] = None
        elif getattr(purchase, 'warehouse_id', None):
            update['current_store_id'] = None
            update['current_warehouse_id'] = purchase.warehouse_id
        if update:
            Barcode.objects.filter(pk=bc.pk).update(**update)


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_multitenant_phase1'),
        ('catalog', '0018_multitenant_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='current_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_barcodes', to='locations.store'),
        ),
        migrations.AddField(
            model_name='barcode',
            name='current_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_barcodes', to='locations.warehouse'),
        ),
        migrations.AddIndex(
            model_name='barcode',
            index=models.Index(fields=['retailer', 'current_store', 'tag'], name='idx_barcode_retailer_store_tag'),
        ),
        migrations.AddIndex(
            model_name='barcode',
            index=models.Index(fields=['retailer', 'current_warehouse', 'tag'], name='idx_barcode_retailer_wh_tag'),
        ),
        migrations.AddConstraint(
            model_name='barcode',
            constraint=models.CheckConstraint(condition=models.Q(('current_store__isnull', True), ('current_warehouse__isnull', True), _connector='OR'), name='barcode_single_current_location'),
        ),
        migrations.RunPython(backfill_barcode_location_from_purchase, migrations.RunPython.noop),
    ]
