# Generated by Django 5.2.8 on 2026-04-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_barcode_current_location"),
        ("locations", "0004_multitenant_phase1"),
        ("purchasing", "0012_multitenant_phase1"),
        ("tenants", "0001_multitenant_phase1"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="barcode",
            name="barcode_single_current_location",
        ),
        migrations.AddConstraint(
            model_name="barcode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("current_store__isnull", False),
                    ("current_warehouse__isnull", False),
                    _negated=True,
                ),
                name="barcode_single_current_location",
            ),
        ),
    ]
