# Generated by Django 5.2.8 on 2026-04-21 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0020_remove_barcode_barcode_single_current_location_and_more"),
        ("tenants", "0002_retailer_azure_blob_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="barcodelabel",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="barcode_labels",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="defectiveproductitem",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="defective_items",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="productcomponent",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_components",
                to="tenants.retailer",
            ),
        ),
    ]
