"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Load environment variables from .env file in project root
# This will look for .env file in the project root directory
env_path = BASE_DIR / '.env'
load_dotenv(dotenv_path=env_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'mtpos-api.intratechnosolutions.com', 'mtims-api.intratechnosolutions.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'corsheaders',
    'backend.core',
    'backend.locations',
    'backend.catalog',
    'backend.inventory',
    'backend.parties',
    'backend.purchasing',
    'backend.pricing',
    'backend.pos',
    'backend.reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DEBUG:
    # Local PostgreSQL configuration for development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'ims'),
            'USER': os.getenv('DB_USER', 'pankajlal'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }

    # DATABASES = {
    #     'default': {
    #         'ENGINE': 'django.db.backends.sqlite3',
    #         'NAME': BASE_DIR / 'db.sqlite3',
    #     }
    # }
else:
    # Production PostgreSQL configuration
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'postgres'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'mtims.cinbnrzrjurt.ap-south-1.rds.amazonaws.com'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'OPTIONS': {
                # Try without SSL first, or set to 'require' if SSL is required
                'sslmode': os.getenv('DB_SSLMODE', 'require'),
                # Connection timeout
                'connect_timeout': 10,
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
if DEBUG:
  STATICFILES_DIRS = [BASE_DIR/'static']
else:
  STATIC_ROOT = BASE_DIR/'static'
MEDIA_ROOT = BASE_DIR/'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'core.User'

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

# CORS
# For development, allow all origins (change to specific origins in production)
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5176",
    "http://localhost:3000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5176",
    "http://127.0.0.1:3000",
    "http://mtpos.intratechnosolutions.com",
    "https://mtpos.intratechnosolutions.com",
    "http://localhost","http://localhost:8765",
    "http://127.0.0.1","http://127.0.0.1:8765",
]
# Allow common headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'errors.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'backend': {
            'handlers': ['console', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'backend.locations': {
            'handlers': ['console', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'backend.reports': {
            'handlers': ['console', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
if not LOGS_DIR.exists():
    os.makedirs(LOGS_DIR, exist_ok=True)

# Azure Function Configuration for Barcode Label Generation
# These can also be set via environment variables: AZURE_FUNCTION_URL and AZURE_FUNCTION_KEY
# Environment variables take precedence if set
AZURE_FUNCTION_URL = os.getenv('AZURE_FUNCTION_URL', '')
AZURE_FUNCTION_KEY = os.getenv('AZURE_FUNCTION_KEY', '')

# Azure Storage Configuration for Blob URL Construction
# These are needed to construct blob URLs before Azure uploads the images
AZURE_STORAGE_ACCOUNT_NAME = os.getenv('AZURE_STORAGE_ACCOUNT_NAME', '')
AZURE_STORAGE_CONTAINER = os.getenv('AZURE_STORAGE_CONTAINER', 'barcode-labels')
AZURE_BLOB_FOLDER = os.getenv('AZURE_BLOB_FOLDER', '').strip()
# Ensure folder path ends with / if provided and not empty
if AZURE_BLOB_FOLDER and not AZURE_BLOB_FOLDER.endswith('/'):
    AZURE_BLOB_FOLDER += '/'

# Azure Storage Account Key (for generating SAS tokens if container is private)
# If container is public, this is not needed
AZURE_STORAGE_ACCOUNT_KEY = os.getenv('AZURE_STORAGE_ACCOUNT_KEY', '')

# Use SAS tokens for blob URLs (set to True if container is private)
# If False and container is public, direct URLs will be used
AZURE_USE_SAS_TOKENS = os.getenv('AZURE_USE_SAS_TOKENS', 'false').lower() == 'true'

# Cache Configuration - OPTIMIZED FOR BEST PERFORMANCE
# =====================================================
# 
# PERFORMANCE RANKING:
# 1. External Redis (BEST) - Fast + Shared across workers
# 2. Database Cache (GOOD) - Shared across workers, reliable
# 3. Local Memory (BAD for production) - Not shared, low cache hit rate
#
# WHY DATABASE CACHE > LOCAL MEMORY on shared hosting:
# - Shared hosting runs multiple workers/processes
# - Local memory cache is NOT shared between workers
# - Each worker has its own cache = low hit rate = more DB queries
# - Database cache IS shared = high hit rate = fewer DB queries
# - Result: Database cache performs BETTER overall despite being "slower" per operation

# Try External Redis first (if configured) - BEST PERFORMANCE
# Only configure cache if not already set (prevents duplicate prints on module reload)
if 'CACHES' not in globals() or not globals().get('CACHES'):
    REDIS_URL = os.getenv('REDIS_URL', '')
    
    if REDIS_URL:
        try:
            # Check if django-redis is installed
            import django_redis
            CACHES = {
                'default': {
                    'BACKEND': 'django_redis.cache.RedisCache',  # Use django-redis backend
                    'LOCATION': REDIS_URL,
                    'OPTIONS': {
                        'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                        'SOCKET_CONNECT_TIMEOUT': 5,
                        'SOCKET_TIMEOUT': 5,
                        'IGNORE_EXCEPTIONS': True,  # Don't crash if Redis is down
                        # Compression: Saves 30-50% memory, faster network transfer, minimal CPU overhead
                        # Question marks in Redis UI are normal (binary data) - cache works perfectly
                        'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
                    },
                    'KEY_PREFIX': 'inventory_manager',
                    'TIMEOUT': 300,  # 5 minutes
                }
            }
            print("✅ Using External Redis Cache (BEST PERFORMANCE)")
        except ImportError:
            # django-redis not installed, fall back to database cache
            REDIS_URL = None
            print("⚠️  Redis URL found but django-redis not installed. Install with: pip install django-redis")
    
    # Fall back to Database Cache - GOOD PERFORMANCE, WORKS EVERYWHERE
    if not REDIS_URL or 'CACHES' not in globals():
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
                'LOCATION': 'cache_table',  # Database table name
                'OPTIONS': {
                    'MAX_ENTRIES': 10000,
                },
                'TIMEOUT': 300,  # 5 minutes
            }
        }
        print("✅ Using Database Cache (Shared across workers - GOOD PERFORMANCE)")
        print("   Run once: python manage.py createcachetable")

# Development override: Use local memory only if explicitly set
# (Not recommended for production due to multi-worker issues)
USE_LOCAL_CACHE = os.getenv('USE_LOCAL_CACHE', 'false').lower() == 'true'
if USE_LOCAL_CACHE and DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
            'OPTIONS': {
                'MAX_ENTRIES': 10000,
            },
            'TIMEOUT': 300,
        }
    }
    print("⚠️  Using Local Memory Cache (Development only - not shared across workers)")