# Generated by Django 5.2.8 on 2025-12-11 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_barcode_tag"),
        ("parties", "0002_unique_phone_ledger_entry"),
        ("purchasing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="directpurchaseline",
            name="purchase",
        ),
        migrations.RemoveField(
            model_name="directpurchaseline",
            name="product",
        ),
        migrations.RemoveField(
            model_name="directpurchaseline",
            name="variant",
        ),
        migrations.RemoveField(
            model_name="grn",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="grn",
            name="purchase_order",
        ),
        migrations.RemoveField(
            model_name="grn",
            name="store",
        ),
        migrations.RemoveField(
            model_name="grn",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="grn",
            name="warehouse",
        ),
        migrations.RemoveField(
            model_name="grnline",
            name="grn",
        ),
        migrations.RemoveField(
            model_name="grnline",
            name="product",
        ),
        migrations.RemoveField(
            model_name="grnline",
            name="variant",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="store",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="warehouse",
        ),
        migrations.RemoveField(
            model_name="purchaseorderline",
            name="purchase_order",
        ),
        migrations.RemoveField(
            model_name="purchaseorderline",
            name="product",
        ),
        migrations.RemoveField(
            model_name="purchaseorderline",
            name="variant",
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("purchase_date", models.DateField()),
                (
                    "bill_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="parties.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "purchases",
                "ordering": ["-purchase_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_items",
                        to="catalog.product",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchasing.purchase",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_items",
                "ordering": ["id"],
            },
        ),
        migrations.DeleteModel(
            name="DirectPurchase",
        ),
        migrations.DeleteModel(
            name="DirectPurchaseLine",
        ),
        migrations.DeleteModel(
            name="GRN",
        ),
        migrations.DeleteModel(
            name="GRNLine",
        ),
        migrations.DeleteModel(
            name="PurchaseOrder",
        ),
        migrations.DeleteModel(
            name="PurchaseOrderLine",
        ),
    ]
