# Generated by Django 5.2.8 on 2025-12-11 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_remove_product_purchase_price_and_more"),
        ("locations", "0002_add_shop_type"),
        ("purchasing", "0002_remove_directpurchaseline_purchase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchases",
                to="locations.store",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchases",
                to="locations.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_items",
                to="catalog.productvariant",
            ),
        ),
    ]
