# Generated by Django 5.2.8 on 2025-12-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0003_purchase_store_purchase_warehouse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("finalized", "Finalized"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
