# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_add_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selling price for this item. If null/0, falls back to purchase price for validation.', max_digits=10, null=True),
        ),
    ]
