# Generated by Django 5.2.8 on 2026-01-19 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_add_composite_indexes"),
        ("locations", "0003_alter_store_shop_type"),
        ("parties", "0007_internalcustomer_internalledgerentry"),
        ("purchasing", "0005_add_selling_price_to_purchase_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["status"], name="idx_purchase_status"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["supplier", "status"], name="idx_purchase_supplier_status"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["-purchase_date", "-created_at"],
                name="idx_purchase_date_created",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseitem",
            index=models.Index(
                fields=["purchase", "product"], name="idx_puritem_pur_product"
            ),
        ),
    ]
