# Generated by Django 5.2.8 on 2026-01-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0006_add_composite_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="is_printed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="printed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
