# Generated by Django 5.2.8 on 2026-02-09 03:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0007_purchaseitem_is_printed_purchaseitem_printed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="shop_quantity",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.000"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="warehouse_quantity",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.000"), max_digits=10
            ),
        ),
    ]
