# Generated by Django 5.2.8 on 2026-04-04 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_safer_fk_on_delete"),
        ("parties", "0019_safer_fk_on_delete"),
        ("purchasing", "0010_soft_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchases",
                to="parties.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_items",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_items",
                to="catalog.productvariant",
            ),
        ),
    ]
