# Generated by Django 5.2.8 on 2026-04-05 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def backfill_purchase_retailer(apps, schema_editor):
    Retailer = apps.get_model('tenants', 'Retailer')
    r = Retailer.objects.filter(code='MT').first()
    if not r:
        r = Retailer.objects.create(code='MT', name='Manish Traders', is_active=True)
    Purchase = apps.get_model('purchasing', 'Purchase')
    Store = apps.get_model('locations', 'Store')
    Warehouse = apps.get_model('locations', 'Warehouse')
    for p in Purchase.objects.filter(retailer_id__isnull=True):
        rid = None
        if p.store_id:
            s = Store.objects.filter(pk=p.store_id).first()
            if s and s.retailer_id:
                rid = s.retailer_id
        if rid is None and p.warehouse_id:
            w = Warehouse.objects.filter(pk=p.warehouse_id).first()
            if w and w.retailer_id:
                rid = w.retailer_id
        Purchase.objects.filter(pk=p.pk).update(retailer_id=rid or r.id)


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_multitenant_phase1"),
        ("parties", "0020_multitenant_phase1"),
        ("purchasing", "0011_safer_fk_on_delete"),
        ("tenants", "0001_multitenant_phase1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="tenants.retailer",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="purchase_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.RunPython(backfill_purchase_retailer, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.UniqueConstraint(
                condition=Q(purchase_number__isnull=False) & ~Q(purchase_number=''),
                fields=("retailer", "purchase_number"),
                name="uniq_purchase_retailer_number_nonnull",
            ),
        ),
    ]
