# Generated by Django 5.2.8 on 2026-04-21 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0014_purchaseitem_tax_rate"),
        ("tenants", "0002_retailer_azure_blob_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_items_explicit",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="purchasestockmovement",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_stock_movements",
                to="tenants.retailer",
            ),
        ),
    ]
