# Generated by Django 5.2.8 on 2025-12-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_add_barcode_to_invoice_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='scanned_barcodes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
