# Generated by Django 5.2.8 on 2025-12-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0005_add_replacement_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("cash", "Cash Invoice"),
                    ("upi", "UPI Invoice"),
                    ("pending", "Pending Invoice"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("cash", "Cash Invoice"),
                    ("upi", "UPI Invoice"),
                    ("pending", "Pending Invoice"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
