# Generated by Django 5.2.8 on 2025-12-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0006_alter_cart_invoice_type_alter_invoice_invoice_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("cash", "Cash Invoice"),
                    ("upi", "UPI Invoice"),
                    ("pending", "Pending Invoice"),
                    ("defective", "Defective Invoice"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
