# Generated by Django 5.2.8 on 2026-01-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0007_alter_invoice_invoice_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("cash", "Cash Invoice"),
                    ("upi", "UPI Invoice"),
                    ("pending", "Pending Invoice"),
                    ("mixed", "Mixed Payment (Cash + UPI)"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("cash", "Cash Invoice"),
                    ("upi", "UPI Invoice"),
                    ("pending", "Pending Invoice"),
                    ("defective", "Defective Invoice"),
                    ("mixed", "Mixed Payment (Cash + UPI)"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
