# Generated by Django 5.2.8 on 2026-01-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0010_repair_label_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("upi", "UPI"),
                    ("bank_transfer", "Bank Transfer"),
                    ("credit", "Credit"),
                    ("refund", "Refund"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
