# Generated by Django 5.2.8 on 2026-01-19 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_add_composite_indexes"),
        ("pos", "0011_alter_payment_payment_method"),
        ("pricing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["cart", "product"], name="idx_cartitem_cart_product"
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceitem",
            index=models.Index(fields=["barcode"], name="idx_invitem_barcode"),
        ),
        migrations.AddIndex(
            model_name="invoiceitem",
            index=models.Index(
                fields=["invoice", "barcode"], name="idx_invitem_inv_barcode"
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceitem",
            index=models.Index(
                fields=["invoice", "product"], name="idx_invitem_inv_product"
            ),
        ),
    ]
