# Generated by Django 5.2.8 on 2026-01-30 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0013_repair_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={"ordering": ["id"]},
        ),
    ]
