# Generated by Django 5.2.8 on 2026-02-02 04:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0014_alter_cartitem_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
