# Generated by Django 5.2.8 on 2026-02-02 18:06
# Fixed: use SeparateDatabaseAndState so we only update Django state.
# The return_items table may already have barcode_id, product_id, etc. from a previous run.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_add_composite_indexes"),
        ("pos", "0014_alter_cartitem_options"),
    ]

    state_operations = [
        migrations.AddField(
            model_name="returnitem",
            name="barcode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_items",
                to="catalog.barcode",
            ),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="return_items",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="product_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="product_sku",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_items",
                to="catalog.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="returnitem",
            name="invoice_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_items",
                to="pos.invoiceitem",
            ),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
    ]
