# Generated by Django 5.2.8 on 2026-02-08 17:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0015_returnitem_barcode_returnitem_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnote",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.000"), max_digits=10
            ),
        ),
    ]
