# Generated by Django 5.2.8 on 2026-02-02 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_add_composite_indexes"),
        ("pos", "0015_alter_invoice_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnitem",
            name="barcode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_items",
                to="catalog.barcode",
            ),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="return_items",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="product_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="product_sku",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_items",
                to="catalog.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="returnitem",
            name="invoice_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_items",
                to="pos.invoiceitem",
            ),
        ),
    ]
