# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_add_returnitem_db_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
