# Generated by Django 5.2.8 on 2026-02-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0018_cart_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="edited_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="repair",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("work_in_progress", "Work in Progress"),
                    ("done", "Done"),
                    ("delivered", "Delivered"),
                    ("not_repaired", "Not Repaired"),
                    ("cancelled", "Cancelled"),
                ],
                default="received",
                help_text="Repair status",
                max_length=20,
            ),
        ),
    ]
