# Generated by Django 5.2.8

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0019_invoice_edited_on_invoice_is_edited_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="purchase_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
