# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0020_cartitem_purchase_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="purchase_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
