# Generated by Django 5.2.8 on 2026-03-05 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0024_add_credit_to_cart_invoice_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expense_date", models.DateField()),
                ("expense_type", models.CharField(max_length=100)),
                (
                    "lender_name",
                    models.CharField(default="Manish Traders", max_length=50),
                ),
                ("borrower_name", models.CharField(max_length=100)),
                (
                    "payment_choices_type",
                    models.CharField(
                        choices=[("CASH", "CASH"), ("ONLINE", "ONLINE")],
                        default="CASH",
                        max_length=100,
                    ),
                ),
                ("expense_amount", models.FloatField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
            },
        ),
    ]
