# Generated by Django 5.2.8 on 2026-03-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0026_alter_repair_contact_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="borrower_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
