# Generated by Django 5.2.8 on 2026-03-10 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0027_make_borrower_name_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
