# Generated by Django 5.2.8 on 2026-03-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0028_alter_invoice_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="expense_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
