# Generated by Django 5.2.8 on 2026-04-03 01:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0029_alter_expenses_expense_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="pos_trade_ins",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="trade_in_credit",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
