# Generated by Django 5.2.8 on 2026-04-04 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_safer_fk_on_delete"),
        ("pos", "0032_invoice_exchange_snapshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="pending_cleared_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_items",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_items",
                to="catalog.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_items",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_items",
                to="catalog.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="returnitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_items",
                to="catalog.product",
            ),
        ),
    ]
