# Generated by Django 5.2.8 on 2026-04-04 16:22

from django.db import migrations, models


def backfill_sold_barcode_value(apps, schema_editor):
    InvoiceItem = apps.get_model("pos", "InvoiceItem")
    Barcode = apps.get_model("catalog", "Barcode")
    for item in InvoiceItem.objects.exclude(barcode_id=None).iterator(chunk_size=500):
        if (getattr(item, "sold_barcode_value", None) or "").strip():
            continue
        try:
            b = Barcode.objects.get(pk=item.barcode_id)
        except Barcode.DoesNotExist:
            continue
        val = (b.barcode or "").strip()[:100]
        if val:
            InvoiceItem.objects.filter(pk=item.pk).update(sold_barcode_value=val)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_safer_fk_on_delete"),
        ("pos", "0033_safer_fk_on_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="sold_barcode_value",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.RunPython(backfill_sold_barcode_value, noop_reverse),
    ]
