# Generated by Django 5.2.8 on 2026-04-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0034_invoiceitem_sold_barcode_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_replacement_return",
            field=models.BooleanField(default=False),
        ),
    ]
