# Generated by Django 5.2.8 on 2026-04-05 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
def backfill_pos_retailer(apps, schema_editor):
    Retailer = apps.get_model('tenants', 'Retailer')
    r = Retailer.objects.filter(code='MT').first()
    if not r:
        r = Retailer.objects.create(code='MT', name='Manish Traders', is_active=True)
    POSSession = apps.get_model('pos', 'POSSession')
    Cart = apps.get_model('pos', 'Cart')
    Invoice = apps.get_model('pos', 'Invoice')
    Return = apps.get_model('pos', 'Return')
    CreditNote = apps.get_model('pos', 'CreditNote')
    Exchange = apps.get_model('pos', 'Exchange')
    Repair = apps.get_model('pos', 'Repair')
    Expenses = apps.get_model('pos', 'Expenses')
    Store = apps.get_model('locations', 'Store')

    def store_rid(store_id):
        if not store_id:
            return None
        s = Store.objects.filter(pk=store_id).first()
        return s.retailer_id if s else None

    for row in POSSession.objects.filter(retailer_id__isnull=True):
        POSSession.objects.filter(pk=row.pk).update(retailer_id=store_rid(row.store_id) or r.id)
    for row in Cart.objects.filter(retailer_id__isnull=True):
        Cart.objects.filter(pk=row.pk).update(retailer_id=store_rid(row.store_id) or r.id)
    for row in Invoice.objects.filter(retailer_id__isnull=True):
        Invoice.objects.filter(pk=row.pk).update(retailer_id=store_rid(row.store_id) or r.id)
    for row in Return.objects.filter(retailer_id__isnull=True):
        inv = Invoice.objects.filter(pk=row.invoice_id).first() if row.invoice_id else None
        rid = inv.retailer_id if inv and inv.retailer_id else r.id
        Return.objects.filter(pk=row.pk).update(retailer_id=rid)
    for row in CreditNote.objects.filter(retailer_id__isnull=True):
        ret = Return.objects.filter(pk=row.return_obj_id).first() if row.return_obj_id else None
        inv = Invoice.objects.filter(pk=ret.invoice_id).first() if ret and ret.invoice_id else None
        rid = inv.retailer_id if inv and inv.retailer_id else r.id
        CreditNote.objects.filter(pk=row.pk).update(retailer_id=rid)
    for row in Exchange.objects.filter(retailer_id__isnull=True):
        inv = Invoice.objects.filter(pk=row.invoice_id).first() if row.invoice_id else None
        rid = inv.retailer_id if inv and inv.retailer_id else r.id
        Exchange.objects.filter(pk=row.pk).update(retailer_id=rid)
    for row in Repair.objects.filter(retailer_id__isnull=True):
        inv = Invoice.objects.filter(pk=row.invoice_id).first() if row.invoice_id else None
        rid = inv.retailer_id if inv and inv.retailer_id else r.id
        Repair.objects.filter(pk=row.pk).update(retailer_id=rid)
    Expenses.objects.filter(retailer_id__isnull=True).update(retailer_id=r.id)


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_multitenant_phase1"),
        ("parties", "0020_multitenant_phase1"),
        ("pos", "0034_invoiceitem_sold_barcode_value"),
        ("pricing", "0003_multitenant_phase1"),
        ("tenants", "0001_multitenant_phase1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_notes",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="exchange",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exchanges",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="expenses",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="possession",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pos_sessions",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="repair",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repairs",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="return",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="returns",
                to="tenants.retailer",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="cart_number",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="creditnote",
            name="credit_note_number",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="exchange_number",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="possession",
            name="session_number",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="repair",
            name="barcode",
            field=models.CharField(
                db_index=True, help_text="Barcode for tracking repair", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="return",
            name="return_number",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.RunPython(backfill_pos_retailer, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                fields=("retailer", "cart_number"), name="uniq_cart_retailer_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.UniqueConstraint(
                fields=("retailer", "credit_note_number"),
                name="uniq_creditnote_retailer_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="exchange",
            constraint=models.UniqueConstraint(
                fields=("retailer", "exchange_number"),
                name="uniq_exchange_retailer_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("retailer", "invoice_number"),
                name="uniq_invoice_retailer_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="possession",
            constraint=models.UniqueConstraint(
                fields=("retailer", "session_number"),
                name="uniq_possession_retailer_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="repair",
            constraint=models.UniqueConstraint(
                fields=("retailer", "barcode"), name="uniq_repair_retailer_barcode"
            ),
        ),
        migrations.AddConstraint(
            model_name="return",
            constraint=models.UniqueConstraint(
                fields=("retailer", "return_number"), name="uniq_return_retailer_number"
            ),
        ),
    ]
