# Generated by Django 5.2.8 on 2026-05-04 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0035_invoice_is_replacement_return"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="replacement_customer_warning",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="replacement_mode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="replacement_source_customers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="accepted_return_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="original_customer_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="original_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="pos.invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="original_invoice_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="pos.invoiceitem",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="original_invoice_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="original_sold_line_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="original_sold_unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="replacement_return_tag",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
