# Generated by Django 5.2.8 on 2026-04-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0035_replacement_pos_invoice_fields"),
        ("pos", "0036_replacement_pos_invoice_fields"),
    ]

    operations = []
