# Generated by Django 5.2.8 on 2026-04-21 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0021_barcodelabel_retailer_defectiveproductitem_retailer_and_more",
        ),
        ("pos", "0037_merge_20260420_1221"),
        ("pricing", "0003_multitenant_phase1"),
        ("tenants", "0002_retailer_azure_blob_folder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items_explicit",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_items_explicit",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments_explicit",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="return_items_explicit",
                to="tenants.retailer",
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["retailer", "cart", "product"],
                name="idx_cartitem_ret_cart_prod",
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceitem",
            index=models.Index(
                fields=["retailer", "barcode"], name="idx_invitem_retailer_barcode"
            ),
        ),
    ]
