# Generated by Django 5.2.8 on 2026-04-21 10:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0038_cartitem_retailer_invoiceitem_retailer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="round_off",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Rounding adjustment applied to total (positive = rounded up, negative = rounded down)",
                max_digits=5,
            ),
        ),
    ]
