# Generated by Django 5.2.8 on 2026-04-22 11:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0039_add_round_off_to_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
