# Generated by Django 5.2.8 on 2026-07-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0041_add_cart_invoice_type_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("cash", "Cash Invoice"),
                    ("upi", "UPI Invoice"),
                    ("pending", "Pending Invoice"),
                    ("defective", "Defective Invoice"),
                    ("credit", "Credit Invoice"),
                    ("mixed", "Mixed Payment (Cash + UPI)"),
                    ("card", "Card Invoice"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
