# Generated by Django 5.2.8 on 2026-07-13 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_product_imagefield_azure"),
        ("credit", "0005_creditcustomer_customer_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creditinvoice",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="creditledgerentry",
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.AddField(
            model_name="creditreturnitem",
            name="credit_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_items",
                to="credit.creditproduct",
            ),
        ),
        migrations.AddField(
            model_name="creditreturnitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_return_items",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="creditreturnitem",
            name="invoice_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="return_items",
                to="credit.creditinvoiceitem",
            ),
        ),
    ]
