# Generated by Django 5.2.8 on 2026-07-25 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0007_creditpayment_source_ledger_entry"),
        ("parties", "0019_safer_fk_on_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCollectionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("reason", "Reason updated"),
                            ("follow_up", "Follow-up date set"),
                            ("auto_bump", "Auto-bumped after payment"),
                            ("cleared", "Follow-up cleared"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("previous_follow_up_date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "credit_collection_events",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="creditcustomer",
            name="collection_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Latest free-text reason / note for collection follow-up",
            ),
        ),
        migrations.AddField(
            model_name="creditcustomer",
            name="next_follow_up_date",
            field=models.DateField(
                blank=True, help_text="Next date to remind / collect payment", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="creditcustomer",
            index=models.Index(
                fields=["next_follow_up_date"], name="idx_cred_cust_followup"
            ),
        ),
        migrations.AddField(
            model_name="creditcollectionevent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_collection_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="creditcollectionevent",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_events",
                to="credit.creditcustomer",
            ),
        ),
        migrations.AddIndex(
            model_name="creditcollectionevent",
            index=models.Index(
                fields=["customer", "-created_at"], name="idx_cred_coll_cust"
            ),
        ),
    ]
