# Generated by Django 5.2.8 on 2025-11-26 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkPriceUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('increase_percent', 'Increase by %'), ('decrease_percent', 'Decrease by %'), ('increase_amount', 'Increase by Amount'), ('decrease_amount', 'Decrease by Amount'), ('set_price', 'Set Price')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('filters', models.JSONField(default=dict)),
                ('affected_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_price_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulk_price_update_logs',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_lists', to='parties.customergroup')),
            ],
            options={
                'db_table': 'price_lists',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('promotion_type', models.CharField(choices=[('cart_total', 'Cart Total Discount'), ('buy_x_get_y', 'Buy X Get Y'), ('category_discount', 'Category Discount'), ('brand_discount', 'Brand Discount'), ('product_discount', 'Product Discount')], max_length=30)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conditions', models.JSONField(default=dict)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_brands', models.ManyToManyField(blank=True, related_name='promotions', to='catalog.brand')),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='promotions', to='catalog.category')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='promotions', to='catalog.product')),
            ],
            options={
                'db_table': 'promotions',
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_items', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_list_items', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'price_list_items',
                'unique_together': {('price_list', 'product', 'variant')},
            },
        ),
    ]
