# Generated by Django 5.2.8 on 2026-04-04 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_safer_fk_on_delete"),
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricelistitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="price_list_items",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="pricelistitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="price_list_items",
                to="catalog.productvariant",
            ),
        ),
    ]
