# Generated by Django 5.2.8 on 2026-04-05 15:10

import django.db.models.deletion
from django.db import migrations, models


def backfill_pricing_retailer(apps, schema_editor):
    Retailer = apps.get_model('tenants', 'Retailer')
    r = Retailer.objects.filter(code='MT').first()
    if not r:
        r = Retailer.objects.create(code='MT', name='Manish Traders', is_active=True)
    PriceList = apps.get_model('pricing', 'PriceList')
    Promotion = apps.get_model('pricing', 'Promotion')
    PriceList.objects.filter(retailer_id__isnull=True).update(retailer_id=r.id)
    Promotion.objects.filter(retailer_id__isnull=True).update(retailer_id=r.id)


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0020_multitenant_phase1"),
        ("pricing", "0002_safer_fk_on_delete"),
        ("tenants", "0001_multitenant_phase1"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelist",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_lists",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotions",
                to="tenants.retailer",
            ),
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.RunPython(backfill_pricing_retailer, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="pricelist",
            constraint=models.UniqueConstraint(
                fields=("retailer", "name"), name="uniq_pricelist_retailer_name"
            ),
        ),
    ]
