# Generated by Django 5.2.8 on 2026-04-21 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0021_barcodelabel_retailer_defectiveproductitem_retailer_and_more",
        ),
        ("pricing", "0003_multitenant_phase1"),
        ("tenants", "0002_retailer_azure_blob_folder"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pricelistitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="bulkpriceupdatelog",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bulk_price_updates",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="pricelistitem",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_list_items_explicit",
                to="tenants.retailer",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pricelistitem",
            unique_together={("retailer", "price_list", "product", "variant")},
        ),
    ]
