# Generated by Django 5.2.8 on 2025-12-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_add_shop_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="shop_type",
            field=models.CharField(
                choices=[
                    ("retail", "Retail Shop"),
                    ("wholesale", "Wholesale Shop"),
                    ("warehouse", "Warehouse"),
                    ("other", "Other"),
                    ("repair", "Repair Shop"),
                ],
                default="retail",
                max_length=20,
            ),
        ),
    ]
