# Generated by Django 5.2.8 on 2026-04-05 15:10

import django.db.models.deletion
from django.db import migrations, models


def backfill_store_warehouse_retailer(apps, schema_editor):
    Retailer = apps.get_model('tenants', 'Retailer')
    r = Retailer.objects.filter(code='MT').first()
    if not r:
        r = Retailer.objects.create(code='MT', name='Manish Traders', is_active=True)
    Store = apps.get_model('locations', 'Store')
    Warehouse = apps.get_model('locations', 'Warehouse')
    Store.objects.filter(retailer_id__isnull=True).update(retailer_id=r.id)
    Warehouse.objects.filter(retailer_id__isnull=True).update(retailer_id=r.id)


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_alter_store_shop_type"),
        ("tenants", "0001_multitenant_phase1"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stores",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warehouses",
                to="tenants.retailer",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="code",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="code",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.RunPython(backfill_store_warehouse_retailer, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.UniqueConstraint(
                fields=("retailer", "code"), name="uniq_store_retailer_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.UniqueConstraint(
                fields=("retailer", "code"), name="uniq_warehouse_retailer_code"
            ),
        ),
    ]
