# Generated by Django 5.2.8 on 2026-04-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_store_auto_populate_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="state",
            field=models.CharField(
                blank=True,
                help_text="State for GST billing (e.g., Delhi, Maharashtra)",
                max_length=100,
            ),
        ),
    ]
