# Generated by Django 5.2.8 on 2026-04-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_store_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="default_invoice_type",
            field=models.CharField(
                choices=[
                    ("cash", "Cash Invoice"),
                    ("upi", "UPI Invoice"),
                    ("pending", "Pending Invoice"),
                    ("defective", "Defective Invoice"),
                    ("credit", "Credit Invoice"),
                    ("mixed", "Mixed Payment (Cash + UPI)"),
                    ("card", "Card Invoice"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
