// Shared mock for the API client module used across screen tests
jest.mock('../../src/api/client', () => {
  const makeCrud = (_base: string) => ({
    list: jest.fn().mockResolvedValue({ data: { results: [] } }),
    get: jest.fn().mockResolvedValue({ data: {} }),
    create: jest.fn().mockResolvedValue({ data: {} }),
    update: jest.fn().mockResolvedValue({ data: {} }),
    delete: jest.fn().mockResolvedValue({ data: {} }),
  });
  return {
    __esModule: true,
    default: {
      defaults: { baseURL: 'http://test/api/v1', headers: { 'Content-Type': 'application/json' }, timeout: 30000 },
      interceptors: {
        request: { use: jest.fn(), handlers: [{}] },
        response: { use: jest.fn(), handlers: [{}] },
      },
      get: jest.fn().mockResolvedValue({ data: {} }),
      post: jest.fn().mockResolvedValue({ data: {} }),
      patch: jest.fn().mockResolvedValue({ data: {} }),
      delete: jest.fn().mockResolvedValue({ data: {} }),
    },
    initApiBaseUrl: jest.fn(),
    setApiBaseUrl: jest.fn(),
    getApiBaseUrl: jest.fn(() => 'http://test/api/v1'),
    authApi: {
      login: jest.fn().mockResolvedValue({ data: { access: 'tok', refresh: 'ref' } }),
      register: jest.fn().mockResolvedValue({ data: { access: 'tok', refresh: 'ref' } }),
      refresh: jest.fn().mockResolvedValue({ data: { access: 'tok' } }),
      me: jest.fn().mockResolvedValue({ data: { id: 1, username: 'admin', email: '', first_name: 'A', last_name: 'U' } }),
    },
    productsApi: {
      ...makeCrud('/products'),
      barcodes: jest.fn().mockResolvedValue({ data: [] }),
      barcodesFull: jest.fn().mockResolvedValue({ data: [] }),
      invoices: jest.fn().mockResolvedValue({ data: [] }),
      byBarcode: jest.fn().mockResolvedValue({ data: {} }),
      variants: jest.fn().mockResolvedValue({ data: [] }),
      generateLabel: jest.fn().mockResolvedValue({ data: {} }),
      generateLabels: jest.fn().mockResolvedValue({ data: {} }),
      getLabels: jest.fn().mockResolvedValue({ data: {} }),
      labelsStatus: jest.fn().mockResolvedValue({ data: {} }),
      regenerateLabels: jest.fn().mockResolvedValue({ data: {} }),
    },
    inventoryApi: {
      stock: {
        list: jest.fn().mockResolvedValue({ data: { results: [] } }),
        get: jest.fn().mockResolvedValue({ data: {} }),
        low: jest.fn().mockResolvedValue({ data: { results: [] } }),
        outOfStock: jest.fn().mockResolvedValue({ data: { results: [] } }),
      },
      adjustments: makeCrud('/adjustments'),
      transfers: makeCrud('/transfers'),
    },
    posApi: {
      carts: {
        ...makeCrud('/carts'),
        getActive: jest.fn().mockResolvedValue({ data: null }),
        getAllActive: jest.fn().mockResolvedValue({ data: [] }),
        getOverview: jest.fn().mockResolvedValue({ data: { results: [] } }),
        addItem: jest.fn().mockResolvedValue({ data: {} }),
        updateItem: jest.fn().mockResolvedValue({ data: {} }),
        deleteItem: jest.fn().mockResolvedValue({ data: {} }),
        removeSku: jest.fn().mockResolvedValue({ data: {} }),
        checkout: jest.fn().mockResolvedValue({ data: {} }),
        bulkBarcodesCheck: jest.fn().mockResolvedValue({ data: {} }),
      },
      invoices: {
        ...makeCrud('/invoices'),
        void: jest.fn().mockResolvedValue({ data: {} }),
        checkout: jest.fn().mockResolvedValue({ data: {} }),
        markCredit: jest.fn().mockResolvedValue({ data: {} }),
        payments: jest.fn().mockResolvedValue({ data: {} }),
        updatePayment: jest.fn().mockResolvedValue({ data: {} }),
        addItem: jest.fn().mockResolvedValue({ data: {} }),
        updateItem: jest.fn().mockResolvedValue({ data: {} }),
        deleteItem: jest.fn().mockResolvedValue({ data: {} }),
        edit: jest.fn().mockResolvedValue({ data: {} }),
        updateFromCart: jest.fn().mockResolvedValue({ data: {} }),
      },
      replacement: {
        check: jest.fn().mockResolvedValue({ data: {} }),
        create: jest.fn().mockResolvedValue({ data: {} }),
        reserveBarcode: jest.fn().mockResolvedValue({ data: {} }),
        updateTag: jest.fn().mockResolvedValue({ data: {} }),
        replace: jest.fn().mockResolvedValue({ data: {} }),
        return: jest.fn().mockResolvedValue({ data: {} }),
        defective: jest.fn().mockResolvedValue({ data: {} }),
        findInvoiceByBarcode: jest.fn().mockResolvedValue({ data: {} }),
        bulkBarcodesCheck: jest.fn().mockResolvedValue({ data: {} }),
        searchInvoices: jest.fn().mockResolvedValue({ data: [] }),
        processReplacement: jest.fn().mockResolvedValue({ data: {} }),
        creditNote: jest.fn().mockResolvedValue({ data: {} }),
      },
      repair: {
        invoices: { list: jest.fn().mockResolvedValue({ data: { results: [] } }), findByBarcode: jest.fn().mockResolvedValue({ data: {} }) },
        getStatusChoices: jest.fn().mockResolvedValue({ data: [] }),
        getDeviceModels: jest.fn().mockResolvedValue({ data: { models: [] } }),
        updateStatus: jest.fn().mockResolvedValue({ data: {} }),
        update: jest.fn().mockResolvedValue({ data: {} }),
        generateLabel: jest.fn().mockResolvedValue({ data: {} }),
      },
      creditNotes: { list: jest.fn().mockResolvedValue({ data: { results: [] } }), get: jest.fn().mockResolvedValue({ data: {} }) },
      expenses: {
        ...makeCrud('/expenses'),
        types: jest.fn().mockResolvedValue({ data: [] }),
        borrowers: jest.fn().mockResolvedValue({ data: [] }),
      },
    },
    customersApi: {
      ...makeCrud('/customers'),
      groups: { list: jest.fn().mockResolvedValue({ data: [] }), create: jest.fn().mockResolvedValue({ data: {} }) },
      ledger: {
        entries: makeCrud('/ledger/entries'),
        byCustomer: jest.fn().mockResolvedValue({ data: { results: [] } }),
        summary: jest.fn().mockResolvedValue({ data: { results: [] } }),
        customerDetail: jest.fn().mockResolvedValue({ data: {} }),
        invoiceItemsByCategory: jest.fn().mockResolvedValue({ data: [] }),
      },
      personalCustomers: makeCrud('/personal-customers'),
      personalLedger: {
        entries: makeCrud('/personal-ledger/entries'),
        summary: jest.fn().mockResolvedValue({ data: { results: [] } }),
        customerDetail: jest.fn().mockResolvedValue({ data: {} }),
      },
      internalCustomers: makeCrud('/internal-customers'),
      internalLedger: {
        entries: makeCrud('/internal-ledger/entries'),
        summary: jest.fn().mockResolvedValue({ data: { results: [] } }),
        customerDetail: jest.fn().mockResolvedValue({ data: {} }),
      },
      paymentReminders: { ...makeCrud('/payment-reminders'), calendar: jest.fn().mockResolvedValue({ data: [] }) },
    },
    catalogApi: {
      categories: { list: jest.fn().mockResolvedValue({ data: [] }), create: jest.fn().mockResolvedValue({ data: {} }) },
      brands: { list: jest.fn().mockResolvedValue({ data: [] }), create: jest.fn().mockResolvedValue({ data: {} }) },
      taxRates: { list: jest.fn().mockResolvedValue({ data: [] }), get: jest.fn().mockResolvedValue({ data: {} }), create: jest.fn().mockResolvedValue({ data: {} }) },
      stores: makeCrud('/stores'),
      warehouses: { list: jest.fn().mockResolvedValue({ data: [] }) },
      barcodes: { updateTag: jest.fn().mockResolvedValue({ data: {} }), bulkUpdateTags: jest.fn().mockResolvedValue({ data: {} }) },
      defectiveProducts: {
        moveOut: jest.fn().mockResolvedValue({ data: {} }),
        moveOuts: { list: jest.fn().mockResolvedValue({ data: { results: [] } }), get: jest.fn().mockResolvedValue({ data: {} }), updateAdjustment: jest.fn().mockResolvedValue({ data: {} }) },
      },
    },
    purchasingApi: {
      purchases: {
        ...makeCrud('/purchases'),
        finalize: jest.fn().mockResolvedValue({ data: {} }),
        redistributeStock: jest.fn().mockResolvedValue({ data: {} }),
        items: { list: jest.fn().mockResolvedValue({ data: [] }), create: jest.fn().mockResolvedValue({ data: {} }), update: jest.fn().mockResolvedValue({ data: {} }), delete: jest.fn().mockResolvedValue({ data: {} }), updatePrinted: jest.fn().mockResolvedValue({ data: {} }) },
      },
      vendorPurchases: { list: jest.fn().mockResolvedValue({ data: { results: [] } }), get: jest.fn().mockResolvedValue({ data: {} }), create: jest.fn().mockResolvedValue({ data: {} }), update: jest.fn().mockResolvedValue({ data: {} }), cancel: jest.fn().mockResolvedValue({ data: {} }) },
      suppliers: makeCrud('/suppliers'),
    },
    pricingApi: {
      priceLists: makeCrud('/price-lists'),
      promotions: makeCrud('/promotions'),
    },
    historyApi: { list: jest.fn().mockResolvedValue({ data: { results: [] } }), get: jest.fn().mockResolvedValue({ data: {} }) },
    reportsApi: {
      salesSummary: jest.fn().mockResolvedValue({ data: {} }),
      topProducts: jest.fn().mockResolvedValue({ data: [] }),
      inventorySummary: jest.fn().mockResolvedValue({ data: {} }),
      revenue: jest.fn().mockResolvedValue({ data: {} }),
      customers: jest.fn().mockResolvedValue({ data: {} }),
      stockOrdering: jest.fn().mockResolvedValue({ data: {} }),
      dashboardKpis: jest.fn().mockResolvedValue({ data: {} }),
    },
    searchApi: { search: jest.fn().mockResolvedValue({ data: {} }) },
  };
});

module.exports = {};
