# Generated by Django 5.2.8 on 2025-12-17 06:42

from django.db import migrations, models
from django.utils import timezone


def set_created_at_for_existing_entries(apps, schema_editor):
    """Set created_at for existing entries that don't have a date"""
    LedgerEntry = apps.get_model('parties', 'LedgerEntry')
    # This migration changes the field to allow null, but existing entries should already have created_at
    # Only update if somehow there are null values (shouldn't happen with auto_now_add)
    # In practice, this should be a no-op since auto_now_add was set before
    pass  # No action needed - existing entries already have created_at


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0002_unique_phone_ledger_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerentry",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(set_created_at_for_existing_entries, migrations.RunPython.noop),
    ]
