# Generated by Django 5.2.8 on 2025-12-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0003_update_ledger_entry_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
