# Generated by Django 5.2.8 on 2026-02-08 15:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0007_internalcustomer_internalledgerentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerentry",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                help_text="Total quantity associated with this entry (e.g. sum of invoice items)",
                max_digits=10,
            ),
        ),
    ]
