# Generated by Django 5.2.8 on 2026-02-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0008_ledgerentry_quantity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="internalledgerentry",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="ledgerentry",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="personalledgerentry",
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
