# Generated by Django 5.2.8 on 2026-02-26 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0009_alter_internalledgerentry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalcustomer",
            name="customer_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="internal_customers",
                to="parties.customergroup",
            ),
        ),
    ]
