# Generated by Django 5.2.8 on 2026-02-26 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0010_internal_customer_customer_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internalledgerentry",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internal_ledger_entries",
                to="parties.customer",
            ),
        ),
    ]
