# Generated by Django 5.2.8 on 2026-03-05 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0011_internal_ledger_entry_customer_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentReminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("due_date", models.DateField()),
                ("due_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payment_reminders", to="parties.customer")),
            ],
            options={
                "db_table": "payment_reminders",
                "ordering": ["due_date", "customer__name"],
            },
        ),
    ]
