# Generated by Django 5.2.8 on 2026-03-05 00:00

from datetime import timedelta
from decimal import Decimal
from django.db import migrations
from django.utils import timezone


def seed_payment_reminders(apps, schema_editor):
    Customer = apps.get_model("parties", "Customer")
    PaymentReminder = apps.get_model("parties", "PaymentReminder")

    if PaymentReminder.objects.exists():
        return

    customers = list(Customer.objects.all().order_by("id")[:5])
    if not customers:
        return

    today = timezone.now().date()
    day_offsets = [2, 5, 9, 14, 21]
    amounts = [Decimal("1500.00"), Decimal("2300.00"), Decimal("900.00"), Decimal("4200.00"), Decimal("3100.00")]

    reminders = []
    for idx, customer in enumerate(customers):
        reminders.append(
            PaymentReminder(
                customer=customer,
                due_date=today + timedelta(days=day_offsets[idx % len(day_offsets)]),
                due_amount=amounts[idx % len(amounts)],
            )
        )

    PaymentReminder.objects.bulk_create(reminders)


def unseed_payment_reminders(apps, schema_editor):
    PaymentReminder = apps.get_model("parties", "PaymentReminder")
    PaymentReminder.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0012_paymentreminder"),
    ]

    operations = [
        migrations.RunPython(seed_payment_reminders, unseed_payment_reminders),
    ]
