# Generated by Django 5.2.8 on 2026-03-05 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0024_add_credit_to_cart_invoice_type"),
        ("parties", "0013_seed_payment_reminders"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentreminder",
            name="is_settled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentreminder",
            name="settled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentreminder",
            name="settled_payment",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="settled_payment_reminders", to="pos.payment"),
        ),
    ]
