# Generated by Django 5.2.8 on 2026-03-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0017_internalledgerentry_source_ledger_entry_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerentry",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
    ]
