# Generated by Django 5.2.8 on 2026-04-04 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0018_add_is_sent_to_ledger_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internalledgerentry",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="internal_ledger_entries",
                to="parties.customer",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="parties.customer",
            ),
        ),
        migrations.AlterField(
            model_name="paymentreminder",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_reminders",
                to="parties.customer",
            ),
        ),
        migrations.AlterField(
            model_name="personalledgerentry",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personal_ledger_entries",
                to="parties.personalcustomer",
            ),
        ),
    ]
