# Generated by Django 5.2.8 on 2026-04-05 15:10

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


def backfill_parties_retailer(apps, schema_editor):
    Retailer = apps.get_model('tenants', 'Retailer')
    r = Retailer.objects.filter(code='MT').first()
    if not r:
        r = Retailer.objects.create(code='MT', name='Manish Traders', is_active=True)
    for model_name in (
        'CustomerGroup',
        'Customer',
        'Supplier',
        'PersonalCustomer',
        'InternalCustomer',
    ):
        Model = apps.get_model('parties', model_name)
        Model.objects.filter(retailer_id__isnull=True).update(retailer_id=r.id)


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0019_safer_fk_on_delete"),
        ("tenants", "0001_multitenant_phase1"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="customergroup",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_groups",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="internalcustomer",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internal_customers",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="personalcustomer",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_customers",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suppliers",
                to="tenants.retailer",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="customergroup",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="code",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.RunPython(backfill_parties_retailer, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("retailer", "name"), name="uniq_customer_retailer_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=Q(phone__isnull=False) & ~Q(phone=''),
                fields=("retailer", "phone"),
                name="uniq_customer_retailer_phone_nonnull",
            ),
        ),
        migrations.AddConstraint(
            model_name="customergroup",
            constraint=models.UniqueConstraint(
                fields=("retailer", "name"), name="uniq_custgroup_retailer_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                condition=Q(code__isnull=False) & ~Q(code=''),
                fields=("retailer", "code"),
                name="uniq_supplier_retailer_code_nonnull",
            ),
        ),
    ]
