# Generated by Django 5.2.8 on 2026-04-21 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0020_multitenant_phase1"),
        ("tenants", "0002_retailer_azure_blob_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalledgerentry",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internal_ledger_entries",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="paymentreminder",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_reminders",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="personalledgerentry",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_ledger_entries",
                to="tenants.retailer",
            ),
        ),
    ]
