# Generated by Django 5.2.8 on 2026-04-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0021_internalledgerentry_retailer_ledgerentry_retailer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="state",
            field=models.CharField(
                blank=True,
                help_text="Customer state for GST bifurcation",
                max_length=100,
            ),
        ),
    ]
