# Generated by Django 5.2.8 on 2026-04-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0022_customer_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="gst_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
