# Generated by Django 5.2.8 on 2026-01-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_add_composite_indexes"),
        ("inventory", "0001_initial"),
        ("locations", "0003_alter_store_shop_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["product", "store"], name="idx_stock_product_store"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["product", "warehouse"], name="idx_stock_product_warehouse"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(fields=["store"], name="idx_stock_store"),
        ),
    ]
