# Generated by Django 5.2.8 on 2026-03-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_add_composite_indexes"),
        ("inventory", "0002_add_composite_indexes"),
        ("locations", "0003_alter_store_shop_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                fields=("product", "variant", "store", "warehouse"),
                name="unique_stock_product_variant_store_warehouse",
            ),
        ),
    ]
