# Generated by Django 5.2.8 on 2026-04-04 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_safer_fk_on_delete"),
        ("inventory", "0003_alter_stock_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_entries",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_entries",
                to="catalog.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adjustments",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adjustments",
                to="catalog.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="stockbatch",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="stockbatch",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="catalog.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransferitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfer_items",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransferitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfer_items",
                to="catalog.productvariant",
            ),
        ),
    ]
