# Generated by Django 5.2.8 on 2026-04-05 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
def backfill_stocktransfer_retailer(apps, schema_editor):
    Retailer = apps.get_model('tenants', 'Retailer')
    r = Retailer.objects.filter(code='MT').first()
    if not r:
        r = Retailer.objects.create(code='MT', name='Manish Traders', is_active=True)
    StockTransfer = apps.get_model('inventory', 'StockTransfer')
    Store = apps.get_model('locations', 'Store')
    for st in StockTransfer.objects.filter(retailer_id__isnull=True):
        rid = None
        if st.from_store_id:
            fs = Store.objects.filter(pk=st.from_store_id).first()
            if fs and fs.retailer_id:
                rid = fs.retailer_id
        if rid is None and st.to_store_id:
            ts = Store.objects.filter(pk=st.to_store_id).first()
            if ts and ts.retailer_id:
                rid = ts.retailer_id
        StockTransfer.objects.filter(pk=st.pk).update(retailer_id=rid or r.id)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_safer_fk_on_delete"),
        ("locations", "0004_multitenant_phase1"),
        ("tenants", "0001_multitenant_phase1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransfer",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_transfers",
                to="tenants.retailer",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="transfer_number",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.RunPython(backfill_stocktransfer_retailer, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="stocktransfer",
            constraint=models.UniqueConstraint(
                fields=("retailer", "transfer_number"),
                name="uniq_stockxfer_retailer_number",
            ),
        ),
    ]
