# Generated by Django 5.2.8 on 2026-04-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_multitenant_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransferitem',
            name='selected_barcodes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
