# Generated by Django 5.2.8 on 2026-04-21 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0021_barcodelabel_retailer_defectiveproductitem_retailer_and_more",
        ),
        ("inventory", "0006_stocktransferitem_selected_barcodes"),
        ("locations", "0005_store_auto_populate_price"),
        ("tenants", "0002_retailer_azure_blob_folder"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stock",
            name="unique_stock_product_variant_store_warehouse",
        ),
        migrations.AlterUniqueTogether(
            name="stockbatch",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="stock",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_entries",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_adjustments",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="stocktransferitem",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_transfer_items",
                to="tenants.retailer",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stockbatch",
            unique_together={
                ("retailer", "product", "variant", "store", "warehouse", "batch_number")
            },
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                fields=("retailer", "product", "variant", "store", "warehouse"),
                name="unique_stock_retailer_product_variant_store_warehouse",
            ),
        ),
    ]
