# Generated by Django 5.2.8 on 2026-09-17 05:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("device_name", models.CharField(blank=True, max_length=128)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("firmware_version", models.CharField(blank=True, max_length=64)),
                ("platform", models.CharField(blank=True, max_length=64)),
                ("push_service_version", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending approval"),
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_attendance_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "attendance_devices",
                "ordering": ["serial_number"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_user_id", models.CharField(db_index=True, max_length=64)),
                ("punch_datetime", models.DateTimeField()),
                ("status", models.IntegerField(default=0)),
                ("verify_mode", models.IntegerField(default=0)),
                ("work_code", models.IntegerField(default=0)),
                ("raw_payload", models.TextField()),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("event_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_events",
                        to="attendance.device",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_events",
                "ordering": ["-punch_datetime", "-id"],
                "indexes": [
                    models.Index(
                        fields=["device", "punch_datetime"],
                        name="attendance__device__90a3b5_idx",
                    ),
                    models.Index(
                        fields=["device_user_id", "punch_datetime"],
                        name="attendance__device__5d1978_idx",
                    ),
                    models.Index(
                        fields=["event_hash"], name="attendance__event_h_04fffc_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceUserMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_user_id", models.CharField(max_length=64)),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Matches salary_book.Employee.employee_id (e.g. EMP-001)",
                        max_length=50,
                    ),
                ),
                ("employee_name", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_mappings",
                        to="attendance.device",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_device_user_mappings",
                "ordering": ["device_id", "device_user_id"],
                "indexes": [
                    models.Index(
                        fields=["employee_id"], name="attendance__employe_0a3c3e_idx"
                    ),
                    models.Index(
                        fields=["device", "device_user_id"],
                        name="attendance__device__da451b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device", "device_user_id"),
                        name="uniq_attendance_device_user",
                    )
                ],
            },
        ),
    ]
