# Generated by Django 5.2.8 on 2026-09-17 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_hardware_attendance_adms"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command_text",
                    models.TextField(
                        help_text="Body after C:{id}: — e.g. DATA UPDATE USERINFO ..."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent to device"),
                            ("ACKED", "Acknowledged"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("purpose", models.CharField(blank=True, max_length=64)),
                ("related_employee_id", models.CharField(blank=True, max_length=50)),
                ("related_pin", models.CharField(blank=True, max_length=64)),
                ("result_code", models.CharField(blank=True, max_length=32)),
                ("result_payload", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("acked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="attendance.device",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_device_commands",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["device", "status", "id"],
                        name="attendance__device__01a348_idx",
                    )
                ],
            },
        ),
    ]
