# Generated by Django 5.2.8 on 2026-10-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_device_commands"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendanceevent",
            options={
                "ordering": ["-punch_datetime", "-id"],
                "verbose_name": "Attendance event",
                "verbose_name_plural": "Attendance events",
            },
        ),
        migrations.AlterModelOptions(
            name="device",
            options={
                "ordering": ["serial_number"],
                "verbose_name": "ADMS device",
                "verbose_name_plural": "ADMS devices",
            },
        ),
        migrations.AlterModelOptions(
            name="devicecommand",
            options={
                "ordering": ["id"],
                "verbose_name": "Device command",
                "verbose_name_plural": "Device commands",
            },
        ),
        migrations.AlterModelOptions(
            name="deviceusermapping",
            options={
                "ordering": ["device_id", "device_user_id"],
                "verbose_name": "Device user mapping",
                "verbose_name_plural": "Device user mappings",
            },
        ),
    ]
