# Generated by Django 5.2.8 on 2026-08-11 06:58

import backend.salary_book.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryBookSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salary_calculation_method",
                    models.CharField(
                        choices=[
                            ("CALENDAR_DAYS", "Calendar Days"),
                            ("FIXED_WORKING_DAYS", "Fixed Working Days"),
                        ],
                        default="CALENDAR_DAYS",
                        max_length=32,
                    ),
                ),
                ("fixed_working_days", models.PositiveSmallIntegerField(default=26)),
                ("max_gps_accuracy_meters", models.PositiveIntegerField(default=100)),
                ("require_gps", models.BooleanField(default=True)),
                ("require_photo", models.BooleanField(default=True)),
                ("require_checkout_gps_photo", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "salary_book_settings",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "mobile",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit Indian mobile number.",
                                regex="^(\\+91)?[6-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("alternate_contact", models.CharField(blank=True, max_length=15)),
                ("address", models.TextField(blank=True)),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=8,
                    ),
                ),
                ("date_of_joining", models.DateField()),
                ("designation", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "monthly_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "salary_calculation_method",
                    models.CharField(
                        choices=[
                            ("INHERIT", "Inherit from settings"),
                            ("CALENDAR_DAYS", "Calendar Days"),
                            ("FIXED_WORKING_DAYS", "Fixed Working Days"),
                        ],
                        default="INHERIT",
                        max_length=32,
                    ),
                ),
                (
                    "fixed_working_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=backend.salary_book.models.employee_photo_upload,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "salary_book_employees",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["employee_id"], name="salary_book_employe_29d075_idx"
                    ),
                    models.Index(
                        fields=["status"], name="salary_book_status_beb40c_idx"
                    ),
                    models.Index(fields=["name"], name="salary_book_name_6502e4_idx"),
                    models.Index(
                        fields=["mobile"], name="salary_book_mobile_acc956_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LeaveRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[("PAID", "Paid Leave"), ("UNPAID", "Unpaid Leave")],
                        max_length=16,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("days", models.PositiveIntegerField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("remarks", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("VOID", "Void")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salary_book_leaves_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leaves",
                        to="salary_book.employee",
                    ),
                ),
            ],
            options={
                "db_table": "salary_book_leaves",
                "ordering": ["-start_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("PAID_LEAVE", "Paid Leave"),
                            ("UNPAID_LEAVE", "Unpaid Leave"),
                            ("HALF_DAY", "Half Day"),
                            ("HOLIDAY", "Holiday"),
                        ],
                        max_length=16,
                    ),
                ),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=backend.salary_book.models.attendance_photo_upload,
                    ),
                ),
                (
                    "check_out_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=backend.salary_book.models.checkout_photo_upload,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "location_accuracy",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("location_captured_at", models.DateTimeField()),
                (
                    "check_out_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "check_out_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "check_out_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("check_out_captured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attendance_method",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("CAMERA", "Camera")],
                        default="MANUAL",
                        max_length=16,
                    ),
                ),
                (
                    "face_verification_status",
                    models.CharField(blank=True, max_length=32),
                ),
                (
                    "face_verification_score",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("face_match_id", models.CharField(blank=True, max_length=64)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salary_book_attendance_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance",
                        to="salary_book.employee",
                    ),
                ),
                (
                    "leave",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_rows",
                        to="salary_book.leaverecord",
                    ),
                ),
            ],
            options={
                "db_table": "salary_book_attendance",
                "ordering": ["-date", "employee_id"],
            },
        ),
        migrations.CreateModel(
            name="SalaryAdvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("remarks", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("VOID", "Void")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salary_book_advances_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advances",
                        to="salary_book.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salary_book_advances_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "salary_book_advances",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SalaryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("gross_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "present_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "absent_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "paid_leave_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "unpaid_leave_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "half_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "holiday_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "unmarked_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "leave_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_advances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("net_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("calculation_method", models.CharField(max_length=32)),
                ("divisor_days", models.PositiveSmallIntegerField()),
                ("daily_salary", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("FINALIZED", "Finalized")],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("PAID", "Paid"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("breakdown", models.JSONField(blank=True, default=dict)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salary_records",
                        to="salary_book.employee",
                    ),
                ),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salary_book_finalized",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "salary_book_salary_records",
                "ordering": ["-year", "-month", "employee_id"],
            },
        ),
        migrations.CreateModel(
            name="SalaryPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("UPI", "UPI"),
                            ("OTHER", "Other"),
                        ],
                        default="CASH",
                        max_length=16,
                    ),
                ),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("remarks", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("VOID", "Void")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salary_book_payments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salary_payments",
                        to="salary_book.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salary_book_payments_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "salary_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="salary_book.salaryrecord",
                    ),
                ),
            ],
            options={
                "db_table": "salary_book_payments",
                "ordering": ["-payment_date", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="leaverecord",
            index=models.Index(
                fields=["employee", "start_date"], name="salary_book_employe_62f231_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverecord",
            index=models.Index(fields=["status"], name="salary_book_status_57a7d7_idx"),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["date"], name="salary_book_date_73c24f_idx"),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["employee", "date"], name="salary_book_employe_2e5cb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["status"], name="salary_book_status_1f5014_idx"),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("employee", "date"), name="uniq_salary_book_att_emp_date"
            ),
        ),
        migrations.AddIndex(
            model_name="salaryadvance",
            index=models.Index(
                fields=["employee", "date"], name="salary_book_employe_22baf7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salaryadvance",
            index=models.Index(fields=["status"], name="salary_book_status_913c08_idx"),
        ),
        migrations.AddIndex(
            model_name="salaryrecord",
            index=models.Index(
                fields=["year", "month"], name="salary_book_year_1bd182_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salaryrecord",
            index=models.Index(fields=["status"], name="salary_book_status_30c1e6_idx"),
        ),
        migrations.AddIndex(
            model_name="salaryrecord",
            index=models.Index(
                fields=["payment_status"], name="salary_book_payment_7318b6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="salaryrecord",
            constraint=models.UniqueConstraint(
                fields=("employee", "year", "month"),
                name="uniq_salary_book_record_emp_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="salaryrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("month__gte", 1), ("month__lte", 12)),
                name="salary_book_record_month_range",
            ),
        ),
        migrations.AddIndex(
            model_name="salarypayment",
            index=models.Index(
                fields=["employee", "payment_date"],
                name="salary_book_employe_1df5c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salarypayment",
            index=models.Index(fields=["status"], name="salary_book_status_141519_idx"),
        ),
    ]
