# Generated by Django 5.2.8 on 2026-08-11 07:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salary_book", "0002_seed_group_and_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="salarybooksettings",
            name="geofence_radius_meters",
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name="salarybooksettings",
            name="office_latitude",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("23.259900"), max_digits=9
            ),
        ),
        migrations.AddField(
            model_name="salarybooksettings",
            name="office_longitude",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("77.412600"), max_digits=9
            ),
        ),
    ]
