# Generated by Django 5.2.8 on 2026-08-11 08:20

import backend.core.storage
import backend.salary_book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salary_book", "0003_salarybooksettings_geofence_radius_meters_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="check_out_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=backend.core.storage.SalaryBookImageStorage(),
                upload_to=backend.salary_book.models.checkout_photo_upload,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=backend.core.storage.SalaryBookImageStorage(),
                upload_to=backend.salary_book.models.attendance_photo_upload,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=backend.core.storage.SalaryBookImageStorage(),
                upload_to=backend.salary_book.models.employee_photo_upload,
            ),
        ),
    ]
