# Generated by Django 5.2.8 on 2026-08-14 08:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


def backfill_employee_schedules(apps, schema_editor):
    Employee = apps.get_model('salary_book', 'Employee')
    Settings = apps.get_model('salary_book', 'SalaryBookSettings')
    settings = Settings.objects.filter(pk=1).first()
    cin = settings.default_check_in if settings else datetime.time(9, 0)
    cout = settings.default_check_out if settings else datetime.time(18, 0)
    Employee.objects.filter(expected_check_in__isnull=True).update(
        expected_check_in=cin, expected_check_out=cout
    )


class Migration(migrations.Migration):

    dependencies = [
        ("salary_book", "0004_attendance_photos_azure_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="is_late",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendance",
            name="minutes_late",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attendance",
            name="payable_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attendance",
            name="rule_penalty_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendance",
            name="rule_remarks",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="attendance",
            name="worked_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employee",
            name="expected_check_in",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="expected_check_out",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salarybooksettings",
            name="default_check_in",
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name="salarybooksettings",
            name="default_check_out",
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.CreateModel(
            name="EmployeeAttendanceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[("CONSECUTIVE_LATE", "Consecutive late days")],
                        default="CONSECUTIVE_LATE",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "late_threshold_minutes",
                    models.PositiveSmallIntegerField(default=30),
                ),
                ("consecutive_late_days", models.PositiveSmallIntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_rules",
                        to="salary_book.employee",
                    ),
                ),
            ],
            options={
                "db_table": "salary_book_attendance_rules",
                "ordering": ["-is_active", "-id"],
                "indexes": [
                    models.Index(
                        fields=["employee", "is_active"],
                        name="salary_book_employe_2266f0_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_employee_schedules, migrations.RunPython.noop),
    ]
