# Generated by Django 5.2.8 on 2026-08-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salary_book", "0005_employee_schedules_rules_and_hourly_pay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="location_accuracy",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="location_captured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
