# Generated by Django 5.2.8 on 2026-09-17 05:54

from django.db import migrations, models


def map_capture_mode_from_require_gps(apps, schema_editor):
    """Existing installs: require_gps True→GEO, False→MANUAL. Do not force HARDWARE."""
    Settings = apps.get_model('salary_book', 'SalaryBookSettings')
    for row in Settings.objects.all():
        row.attendance_capture_mode = 'GEO' if row.require_gps else 'MANUAL'
        row.save(update_fields=['attendance_capture_mode'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("salary_book", "0006_nullable_attendance_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="salarybooksettings",
            name="attendance_capture_mode",
            field=models.CharField(
                choices=[
                    ("HARDWARE", "Hardware (fingerprint / card)"),
                    ("GEO", "Geo (GPS + selfie)"),
                    ("MANUAL", "Manual"),
                ],
                default="HARDWARE",
                max_length=16,
            ),
        ),
        migrations.RunPython(map_capture_mode_from_require_gps, noop_reverse),
        migrations.AlterField(
            model_name="attendance",
            name="attendance_method",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("CAMERA", "Camera"),
                    ("HARDWARE", "Hardware"),
                ],
                default="MANUAL",
                max_length=16,
            ),
        ),
    ]
