# Generated by Django 5.2.8 on 2026-10-07 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0019_safer_fk_on_delete"),
        ("salary_book", "0009_salarybooksettings_machine_time_delta_locked"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="mtshop_customer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="salary_book_employee",
                to="parties.customer",
            ),
        ),
        migrations.AddField(
            model_name="salaryadvance",
            name="source",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("MTSHOP", "MT Shop")],
                db_index=True,
                default="MANUAL",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="salaryadvance",
            name="source_internal_entry_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="salaryadvance",
            name="source_invoice_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="salaryadvance",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("VOID", "Void"), ("PAID", "Paid")],
                default="ACTIVE",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="salaryadvance",
            index=models.Index(
                fields=["source", "status"], name="salary_book_source_b1ea7a_idx"
            ),
        ),
    ]
