# Generated by Django 5.2.8 on 2026-10-05 04:29

import backend.core.models
import backend.core.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0004_alter_auditlog_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomNavLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField(max_length=500)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=backend.core.storage.CustomNavLogoStorage(),
                        upload_to=backend.core.models.custom_nav_logo_upload,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="custom_nav_links", to="auth.group"
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_nav_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "custom_nav_links",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
