# Generated by Django 5.2.8 on 2026-04-05 15:10

import django.db.models.deletion
from django.db import migrations, models


def backfill_user_retailer(apps, schema_editor):
    Retailer = apps.get_model('tenants', 'Retailer')
    r = Retailer.objects.filter(code='MT').first()
    if not r:
        r = Retailer.objects.create(code='MT', name='Manish Traders', is_active=True)
    User = apps.get_model('core', 'User')
    User.objects.filter(retailer_id__isnull=True).exclude(is_superuser=True).update(retailer_id=r.id)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_auditlog_action"),
        ("tenants", "0001_multitenant_phase1"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="tenants.retailer",
            ),
        ),
        migrations.RunPython(backfill_user_retailer, migrations.RunPython.noop),
    ]
