# Generated by Django 5.2.8 on 2026-04-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_auditlog_action_replacement_pos"),
        ("core", "0010_expand_auditlog_actions"),
    ]

    operations = []
