# Generated by Django 5.2.8 on 2026-04-20 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_role_management_permissions"),
        ("tenants", "0001_multitenant_phase1"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetailerDashboardViewConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_visibility", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "retailer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_view_config",
                        to="tenants.retailer",
                    ),
                ),
            ],
            options={
                "db_table": "retailer_dashboard_view_configs",
            },
        ),
    ]
