# Generated by Django 5.2.8 on 2026-04-21 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_retailerdashboardviewconfig"),
        ("locations", "0005_store_auto_populate_price"),
        ("tenants", "0002_retailer_azure_blob_folder"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userstorerole",
            name="uniq_user_store_role",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_logs_created_43fcd6_idx",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="tenants.retailer",
            ),
        ),
        migrations.AddField(
            model_name="userstorerole",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_store_roles",
                to="tenants.retailer",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="key",
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["retailer", "-created_at"], name="idx_audit_retailer_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="setting",
            constraint=models.UniqueConstraint(
                fields=("retailer", "key"), name="uniq_retailer_setting_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="userstorerole",
            constraint=models.UniqueConstraint(
                fields=("retailer", "user", "store"),
                name="uniq_retailer_user_store_role",
            ),
        ),
    ]
